export default interface Ranking {
  competition_id: string;
  person_name: string;
  person_id: string;
  person_country_id: string;
  wca_record: string;
  wca_pos: number;
  best_score: number;
  best_result: number;
  mean_score: number | undefined;
  value1: number | undefined;
  value2: number | undefined;
  value3: number | undefined;
  score1: number | undefined;
  score2: number | undefined;
  score3: number | undefined;
  continent_id: string;
  startdate: Date;
  regional_record: string;
  regional_mean_record: string;
  pos: number;
  world_rank: number;
  continent_rank: number;
  country_rank: number;
  wca_world_rank: number;
  wca_continent_rank: number;
  wca_country_rank: number;
  rank?: number;
  wca_rank?: number;
}
